### ISSUE TITLE
Language Negotiation Not Working for Specific Countries

### ISSUE THREAD

**Issue by calioto** [angular-translate/angular-translate#1753] opened 2017-06-19 20:27 UTC
I am trying to get a country specific version of a language to display in my application, but the application is always using the default version in my application. For example, if a user's browser is setup to use Canadian French (fr_CA), then I want my fr_CA translations to display. For any other version of French (fr*), I want my fr_FR translations to display. However, in my application, even if the browser is set for Canadian French, the France French translations are displaying.

Here's an excerpt from my code:
```javascript
		var langMap = {
			'de*': 'de',
			'en*': 'en',
			'es*': 'es',
			'fr_CA': 'fr_CA',
			'fr*': 'fr_FR',
			'it*': 'it',
			'ja*': 'ja',
			'ko*': 'ko',
			'pt*': 'pt',
			'zh_TW' : 'zh_TW',
			'zh*' : 'zh_CN',
			'*': 'en'	// Must be listed last
		};

		$translateProvider
			.translations('de', SRNEXT_WIDGET_NLS_DE)
			.translations('en', SRNEXT_WIDGET_NLS_EN)
			.translations('es', SRNEXT_WIDGET_NLS_ES)
			.translations('fr_CA', SRNEXT_WIDGET_NLS_FR_CA)
			.translations('fr_FR', SRNEXT_WIDGET_NLS_FR_FR)
			.translations('it', SRNEXT_WIDGET_NLS_IT)
			.translations('ja', SRNEXT_WIDGET_NLS_JA)
			.translations('ko', SRNEXT_WIDGET_NLS_KO)
			.translations('pt', SRNEXT_WIDGET_NLS_PT)
			.translations('zh_CN', SRNEXT_WIDGET_NLS_ZH_CN)
			.translations('zh_TW', SRNEXT_WIDGET_NLS_ZH_TW)
			.registerAvailableLanguageKeys(['de', 'en', 'es', 'fr_CA', 'fr_FR', 'it', 'ja', 'ko', 'pt', 'zh_CN', 'zh_TW'], langMap)
			.determinePreferredLanguage()
			.fallbackLanguage(['en']);
```

I am using angular-translate 2.13, angular 1.5.8 and various browsers.

Any help would be appreciated. Thanks.

~ Christopher

**Comment by knalli** [comment] 2017-06-22 11:40
Maybe the lang key is not as expected? We have an additional API for the language tag resolving step calling `uniformLanguageTag`, see https://angular-translate.github.io/docs/#/guide/07_multi-language#multi-language_determining-preferred-language-automatically

**Comment by calioto** [comment] 2017-06-22 17:07
I added that to my code and the application still displayed France French instead of Canadian French. Here's my code snippet. Any other ideas?

```javascript
		$translateProvider
			.translations('de', SRNEXT_WIDGET_NLS_DE)
			.translations('en', SRNEXT_WIDGET_NLS_EN)
			.translations('es', SRNEXT_WIDGET_NLS_ES)
			.translations('fr_CA', SRNEXT_WIDGET_NLS_FR_CA)
			.translations('fr_FR', SRNEXT_WIDGET_NLS_FR_FR)
			.translations('it', SRNEXT_WIDGET_NLS_IT)
			.translations('ja', SRNEXT_WIDGET_NLS_JA)
			.translations('ko', SRNEXT_WIDGET_NLS_KO)
			.translations('pt', SRNEXT_WIDGET_NLS_PT)
			.translations('zh_CN', SRNEXT_WIDGET_NLS_ZH_CN)
			.translations('zh_TW', SRNEXT_WIDGET_NLS_ZH_TW)
			.registerAvailableLanguageKeys(['de', 'en', 'es', 'fr_CA', 'fr_FR', 'it', 'ja', 'ko', 'pt', 'zh_CN', 'zh_TW'], langMap)
			.uniformLanguageTag('bcp47') // enable BCP-47, must be before determinePreferredLanguage!
			.determinePreferredLanguage()
			.fallbackLanguage(['en']);

```

**Comment by knalli** [comment] 2017-06-22 18:06
I have prepared a demo, see here https://plnkr.co/edit/rJNHzQ?p=preview

The relevant code have been extracted in the override object. `default` is okay when using the underscore variant.

**Comment by knalli** [comment] 2017-10-03 17:03
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.

**Closed by knalli** 2017-10-03 17:03 UTC
Labels: waiting
