### ISSUE TITLE
Using $translateProvider.useLoader, the addPart/refresh combination does not work properly for the frist element's translation.

### ISSUE THREAD

**Issue by virtualit786** [angular-translate/angular-translate#399] opened 2014-02-25 09:43 UTC
Hi Pascal,

Here is the config 
```js
.config(['$translateProvider', '$translatePartialLoaderProvider', function ($translateProvider, $translatePartialLoaderProvider) {

    $translateProvider.useLoader('$translatePartialLoader', {
        urlTemplate: 'i18n/{lang}/{part}.json'
    });
    $translateProvider.preferredLanguage('en-EN');
    $translatePartialLoaderProvider.addPart('main');
}])
```
Tranlsation files are :- 
i18n/en-EN/main.json
i18n/en-EN/pa.json
i18n/fr-FR/main.json
i18n/fr-FR/pa.json

The files have few common elements for example page heading is common in all files which refers to the heading of that particular page.

MainCtrl for mainview.html
```js
angular.module('appApp')//organization-definition
    .controller('MainCtrl', ['$scope', '$translate', '$translatePartialLoader',
        function ($scope,   $translate, $translatePartialLoader) {            
            $translatePartialLoader.addPart('main');
            $translate.refresh();
        }
    ]);
```
PaAddCtrl for paview.html
```js
angular.module('appApp')
    .controller('PaAddCtrl', ['$scope', '$translate', '$translatePartialLoader',
        function ($scope, $translate, $translatePartialLoader) {
            $translatePartialLoader.addPart('positions');
            $translate.refresh();
        }])
```
When the app starts, MainCtrl is the one so the language part sets up to main and it works fine. When I move to PaAddCtrl from MainCtrl, then the translation of first element does not come from the positions.json file but instead comes from the main.json file. 
And same thing happens when I move from PaAddCtrl's paview.html to MainCtrl's main.html. 

What am I doing wrong? Can you please point it out and help me fix this?

**Comment by gtbuchanan** [comment] 2015-01-19 17:12
Yes, this is still a problem. See [this][0] plunker taken from [this][1] answer on StackOverflow. I can confirm this is also still the case if I use the `$translate` service in the controller after `$translate.refresh` is called.

[0]: http://plnkr.co/edit/sZC2XST8BMZcMCYbgtxt?p=preview
[1]: http://stackoverflow.com/a/25070429/1409101

**Comment by gtbuchanan** [comment] 2015-01-19 23:21
This is my current undesirable workaround:

    app.run(['$rootScope', '$translate', '$interval', function ($rootScope, $translate, $interval) {
        $rootScope.$on('$translatePartialLoaderStructureChanged', function () {
            if ($translate.use()) {
                $translate.refresh();
            } else {
                var token = $interval(function () {
                    if (!$translate.use()) return;
                    $translate.refresh();
                    $interval.cancel(token);
                }, 10);
            }
        });
    }]);

The issue is `$translate.refresh` is usually executed in the controller before the initial load of the language has completed and `$uses` is set, so `$translate.refresh` actually just does nothing in this case.

I would think `$translate.refresh` either needs to consider `$nextLang`, or `$translate.use` needs to execute the pending refresh when it finishes.

Our locale is being loaded from a cookie so the translations are loaded in the `run` block. Additionally. we do not have a fallback language set on the client as this is handled in our server.

**Comment by knalli** [comment] 2015-04-12 17:19
ping @DWand

**Comment by DWand** [comment] 2015-04-12 19:56
@knalli, it seams that this issue is not resolved yet. I was unable to operate with the provided plunker. Also I did not look at the example on GitHub as it is huge and has a lot of directories.

But, there are at least two possible things which can lead to an unexpected behavior here.

1. Race condition between added parts in the loader. It can happen if different parts have some identical translation keys. Actually it is not the race condition here, but very similar and leads to unpredictable result. To solve this thing the developer has either to avoid a usage of identical translation ids or delete old parts before the `refresh()` method is called. Also, at the moment we have additional tools to help to fight this situation: the `getRegisteredParts` method and priority of the parts.

2. As for the question from stackoverflow, @gtbuchanan is right. There is a problem with synchronization between `use()` and `refresh()` methods.

**Comment by DWand** [comment] 2015-04-12 19:58
At the moment I can suggest to read this comment https://github.com/angular-translate/angular-translate/issues/306#issuecomment-66763693

**Comment by ena1106** [comment] 2015-09-10 11:19
@egervari Thank you so much. Putting the addPart and refresh inside the controller fixed the issue I was having. I generate pdf from html using the tool wkhtmltopdf from command line. With the code in the resolve of the route, generated pdf had all the keys instead of the translations.

**Comment by knalli** [comment] 2016-03-06 14:17
> Yes, this is still a problem. See this plunker taken from this answer on StackOverflow. I can confirm this is also still the case if I use the $translate service in the controller after $translate.refresh is called.

It seems the partial loader will not work without using `.use()`.

```diff
+$translateProvider.use('EN');
$translateProvider.preferredLanguage('EN');
```

Given that, I would likely close this issue here. The partial loader is well known not being optimized or efficient. Any contributions making it better are welcome.

**Comment by knalli** [comment] 2016-03-20 14:36
Closed due inactivity. Enhancements for the partial loader already addressed in the linked issues.

**Closed by knalli** 2016-03-20 14:36 UTC
Labels: waiting
