### ISSUE TITLE
Angular 1.6 support

### ISSUE THREAD

**Issue by alippai** [angular-translate/angular-translate#1657] opened 2016-12-02 13:56 UTC
Bower says Angular 1.6 is incompatible with angular-translate 2.13.0:
`angular#>=1.2.26 <1.6 which resolved to 1.5.9 and is required by angular-translate#2.13.0`

**Comment by alippai** [comment] 2016-12-02 14:02
I wanted to add a PR as well, but I can't find the given constraint. :S

**Comment by knalli** [comment] 2016-12-02 16:36
Hi,

exactly this constraint is in the shadow repo only.

However, before adding this we have to ensure we are actually compatible with 1.6. It is not adding a version only. That is not so easy. If you know what you are doing, you can override this version on your own always any time.

The test targets are managed by:
* existence of a directory here: https://github.com/angular-translate/angular-translate/tree/46ba474b9be218ed26ab71822f398cb5409440c8/test_scopes
* an entry for TravisCI here https://github.com/angular-translate/angular-translate/blob/46ba474b9be218ed26ab71822f398cb5409440c8/.travis.yml#L20-L25

**Comment by knalli** [comment] 2016-12-06 18:47
Fine, tests added but there is something failing. That's why we don't open the version range in advance.

However, you can always override the version with bower resolutions.

**Comment by alippai** [comment] 2016-12-09 15:56
It's stable now: https://github.com/angular/angular.js/blob/master/CHANGELOG.md
Maybe the release notes and breaking changes will help to identify the problem.

**Comment by evilaliv3** [comment] 2016-12-22 14:00
@knalli any new on this front?

**Comment by knalli** [comment] 2016-12-22 14:04
Sorry, no time yet. PR is still open, also for anyone helping outstanding issues.

**Comment by spock123** [comment] 2016-12-23 08:29
The issue is with the $http service breaking changes

**Comment by knalli** [comment] 2017-01-01 20:38
The PR #1659 is still open. The issue is actually a promise rejection check (introduced in AJS 1.6). If someone can help out, that would be fine. Make the things faster.

**Comment by z3ntu** [comment] 2017-02-06 10:56
Can I expect this to be fixed in the near future?

**Comment by knalli** [comment] 2017-02-06 11:51
Well, #1659 is still open for everyone.

I'd sit down at this yesterday, but don't have a solution. Maybe it's a test scenario issue only (with custom $httpBackend.whenAsync implementation).

**Comment by knalli** [comment] 2017-02-06 23:05
in canary landed

**Closed by knalli** 2017-02-06 23:05 UTC
Labels: Feature

**Comment by evilaliv3** [comment] 2017-02-08 15:39
cool @knalli thanks!

is there any ETA for the release?

**Comment by knalli** [comment] 2017-02-13 15:32
-> already released
