### ISSUE TITLE
The key is returned until language file is available

### ISSUE THREAD

**Issue by pedrocatre** [angular-translate/angular-translate#1018] opened 2015-04-28 10:51 UTC
If we use {{::'NEXT_BTN' | translate}} and the language file is still being fetched we get the key 'NEXT_BTN'. And then when the language file is available nothing changes because it was one time binded.

Is there a way to change this behaviour so we get undefined? If I recall correctly angular's one time binding is smart enough to only one time bind after the results is no longer undefined.

**Comment by knalli** [comment] 2015-04-28 11:18
One time binding conflicts with the asynchronous pattern (here: loading of translations). You should be aware that in case of asynchronous loading your page will be blank.

While you can [add a custom error handler](http://angular-translate.github.io/docs/#/guide/17_custom-error-handler) returning always undefined, this will not solve your actual problem: Here a demo http://plnkr.co/edit/F9bsLhIOKCNpkPR6Xbrc?p=preview The issue is we are treating undefined as being no specific result (in case of a log handler).

So: No, both combinations are not possible right now.

**Comment by pedrocatre** [comment] 2015-04-28 12:45
Ok thank you for the detailed explanation!

I guess for now the best choice is to have the translations in the code. I cannot afford two way data binding in the translations in one of the views that can have more than 100 form fields being displayed with several bindings :/ or I can fork and make the change, seems easy enough.

"treating undefined as being no specific result": would it make sense to make this behaviour configurable (or just change the default behaviour) given how one time binding works?

**Comment by knalli** [comment] 2015-04-28 12:56
Actually, 100 bindings aren't so bad. But this decision is up to you.

An alternative strategy could be the manual way avoiding filter and directive using the service directly.

```js
app.controller('YourController', function ($translate) {
  var self = this;
  this.texts = {};
  // maybe listen for the first initial language laded (via event)
  $translate(['array', 'with', 'all', 'your-keys'])
    .then( function (translations) {self.texts = translations;});
});
``

> "treating undefined as being no specific result": would it make sense to make this behaviour configurable 

I actually  do not know the consequences or the intention. The main idea of the handler was originally logging purpose (so undefined would be the noop).

So: Yes, an additional behavior setting could be added. Perhaps you  make a PR? :)

Closing this.

**Closed by knalli** 2015-04-28 12:56 UTC
Labels: FAQ, question

**Comment by pedrocatre** [comment] 2015-04-28 13:21
I did not mean 100 bindings, I know that would be fine. I said more than 100 elements each with their own bindings. It is fine on my machine but on a slower machine running ie9 it has an impact.

Thanks again. For now I will just import the language files, in the short term it makes it even faster to load because it does not have to make an extra request for a file, and I only have two languages. If this changes down the line I'll probably make a PR.
