### ISSUE TITLE
Using forceLanguage does not load language automatically

### ISSUE THREAD

**Issue by elpeq** [angular-translate/angular-translate#1389] opened 2016-02-01 15:44 UTC
Hello,

tested in angular-translate 2.9

forceLanguage doesn't work if StaticFilesLoader is used:
$translateProvider.useStaticFilesLoader

Yann

**Comment by knalli** [comment] 2016-02-09 22:04
@elpeq Please provide always a working demo with your issue.

I've made a demo, but cannot see any problem with this: http://plnkr.co/edit/iiBTCvK3t2qwUeTZiamd?p=preview

**Comment by craig-at-rsg** [comment] 2016-02-10 19:26
@elpeq Is a language failing to load, and then you're using forceLanguage? I handled the rejection from the static file loader and that let me continue. 

return $translateStaticFilesLoader({
							prefix: 'languages/',
							key: options.key,
							suffix: '.json'
						})['catch'](function () { return {}; })

**Comment by elpeq** [comment] 2016-02-15 08:46
Hello @knalli 
I've adapted your demo and added a 3 language pt_PT that shows, that the force language doesn't work. 
http://plnkr.co/edit/6BJPNGqS0YYo2fBJb8jf?p=preview

**Comment by knalli** [comment] 2016-02-15 09:22
Alright: the language will be not loaded automatically.

**Comment by knalli** [comment] 2016-03-20 16:21
Fixed with 14bc956

**Closed by knalli** 2016-03-20 16:21 UTC
Labels: bug, Contribution Welcome

**Comment by almeidap** [comment] 2016-04-20 08:46
Forcing a language is now working in version 2.11.0 but it produces errors when trying to switch to another language afterwards:

    angular.js:13236 TypeError: Cannot read property 'key' of undefined
        at angular-translate.js:2216
        at processQueue (angular.js:15552)
        at angular.js:15568
        ...

You should be able to reproduce the issue if you click in any language button on the updated demo Plunk:
http://plnkr.co/edit/3YVgipajDFwLuYBVVBeh?p=preview

FYI, angular-translate determines my preferred language as French, which is correct.

**Comment by almeidap** [comment] 2016-04-20 13:07
In fact after some more testing, it looks like forcing a translation only works properly when using the `translate` pipe. Take a look to the improved demo again:
http://plnkr.co/edit/3YVgipajDFwLuYBVVBeh?p=preview

* When using the `translate-force` directives, it fails radomly (probably due to the promise mechanism behind the scene).
* Note that I had to comment the `$translateProvider.determinePreferredLanguage()` call as it seems to conflict with `$translateProvider.fallbackLanguage()` (see #1075) and breaks completely `translate-force`.

Unless there is something wrong in the demo, this issue should be reopened again.

**Comment by knalli** [comment] 2016-04-20 17:07
We don't reopen.. the workflow is always a new issue. => #1471
