### ISSUE TITLE
getFirstBrowserLanguage returns wrong language on Chrome 46 on Windows 7

### ISSUE THREAD

**Issue by jgsacris** [angular-translate/angular-translate#1283] opened 2015-11-02 11:19 UTC
At least when running on a german version of Windows 7 the nav.languages array in chrome lists 'en-US'
as the first element, and 'en' in second, even though the nav.language property is correctly listed as 'de'. 
Please consider first analysing the browserLanguagePropertyKeys and the the nav.language array, since it seems that the order of this array is not guarantied to return the best answer.

PD. It would be useful if one could read the $preferredLanguage property from outside the library.

**Comment by tspaeth** [comment] 2015-11-02 11:26
I can't reproduce your issue. If I ask my Chrome Version 46.0.2490.80 m (64-bit) on Windows 7 (German) for window.navigator.languages looks like this:

```
["de-DE", "de", "en-US", "en", "fr"]
```

What does chrome tell you if you enter "window.navigator.languages" in your console?

**Comment by jgsacris** [comment] 2015-11-02 13:49
That is strange, I have the same version of Chrome but 32-bit and I get:
["en-US", "en", "de", "es"]
"window.navigator.language" returns "de" though.

**Comment by tspaeth** [comment] 2015-11-02 13:54
How do your chrome settings look like?

![image](https://cloud.githubusercontent.com/assets/5180973/10883323/856b75ec-8171-11e5-84c3-b4f445abf84d.png)

**Comment by jgsacris** [comment] 2015-11-03 09:35
You are right! Indeed the order of the languages on the settings is the order of the languages array of the navigator. Still I find strange that the language attribute returns "de", the language of the chrome interface is german and I still get an english website, but I guess if thats the preference that the user set it should be OK!
Thanks

**Comment by tspaeth** [comment] 2015-11-03 09:39
Closing it as there is no open points from my side.

**Closed by tspaeth** 2015-11-03 09:39 UTC
