### ISSUE TITLE
Filter convert accents to entities with 'sanitize' strategy (directive doesn't)

### ISSUE THREAD

**Issue by raphaelyancey** [angular-translate/angular-translate#1434] opened 2016-03-09 12:15 UTC
### Subject of the issue
The filter and the directive output different result with `$tp.useSanitizeValueStrategy('sanitize')`.
Translation via the **filter** converts accents to their HTML entities (`é` to `&#233;`).
Translation via the **directive** keeps accents ok.

### Your environment
* angular-translate 2.8.1
* angular 1.2.28
* Chrome 49 & Firefox 45 on OS X (but not a browser issue I think)

### Steps to reproduce
* Create a translation with accents in it
* Print it with the directive, and the filter

Here is a [working demo](https://plnkr.co/edit/DaQJHXI1FwYIaYiX5z3g?p=preview)

### Expected behaviour
Filter and directive behaving the same way.

### Actual behaviour
Filter and directive don't behave the same way.

**Comment by raphaelyancey** [comment] 2016-03-11 13:22
I didn't see #1101. The problem is fixed with `escapeParameters` but with this strategy, boolean translate-values are cast to strings. Therefore I must do `{{ bool == 'true' ? 'truthy' : 'falsey' }}` instead of a natural `{{ bool ? 'truthy' : 'falsey' }}` in my translations (and that's what made me dig the problem in the first place).

**Comment by knalli** [comment] 2016-03-12 20:15
Short: The filter output is not completely in our control because it is managed by AJS itself.

And right: This is a duplicate of #1101.

**Closed by knalli** 2016-03-12 20:15 UTC
