### ISSUE TITLE
$translate.refresh() doesn't clear all keys of $translateTable.

### ISSUE THREAD

**Issue by gsaini** [angular-translate/angular-translate#988] opened 2015-04-07 08:14 UTC
I am using angular-translate on my project. Where I loads the vocabulary on module basis. Now on change preference on application level, I need to clear all the previously loaded vocabularies. I am using $translate.refresh() to load the keys again on further navigation on modules but it loads the translates for current used key only while I want to load the translations keys again on navigate on that particular module after use $translate.refresh() once.

**Comment by DWand** [comment] 2015-04-07 12:13
Hello, @gsaini.

The purpose (or, probably, task) of the `$translate.refresh()` method is to refresh translation tables which are currently present in the `$translate` module. So, this method deletes old translation tables from the module and asynchronously loads their newer version.

If you want to *change* the translation table, then you have to combine the `$translate.refresh()` method with some loader. Something like this:

1. Configure the loader to return another translation table
2. Call the `$translate.refresh()` method

**Comment by gsaini** [comment] 2015-04-11 10:11
Can you please elaborate which you suggested above or any eaxmple?

& I suggest, It would be great if you can provide $translate.refreshAll() method which can be use to clear all translate tables.

**Comment by DWand** [comment] 2015-04-12 20:33
Hm... Really there is a problem. Thanks, @gsaini.

I'm not sure if I am right, but this scenario will lead to error:
1) Use some `lang1` language
2) Use some `lang2` language
3) Refresh translation tables
4) Use the `lang1` language

Here we will get the old version of the `lang1` translation table. It happens because we delete only those translation tables which were re-loaded from the server.

See here: https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/src/service/translate.js#L1651-L1654

@angular-translate/core, is it appropriate to delete **all** existing translation tables in case the new ones were loaded successfully? Do we need to re-load only the current languages or all languages which were loaded during the current session (this question can also affect separation of fallback language handling)?

**Comment by knalli** [comment] 2015-04-18 20:19
In general, a `refresh()` should refresh the things. So it is looking from the outside like being a bug when a translation has not been refreshed (case: a language is neither a fallback nor active but has been used in the past). I'm not sure if we really should *reload* all the languages. It would be sufficient ditching them only.

However, one problem is not solved and perhaps that's the original intent for that refresh strategy: If the reloading language was not injected via an async loader (i.e. predefined statically), the translations would be gone forever. This is actually true already nowadays, but only when being a fallback or in use.

**Comment by DWand** [comment] 2015-04-18 20:49
@knalli, they won't be missed. An Error will be thrown from the `refresh` method in case a loader is not specified.

Okay, then. I'll remove all translation tables in that case.

**Comment by knalli** [comment] 2015-04-18 21:55
@DWand  You do not get me right: We do not define loaders for a specific language, but in general.

1. Setup phase: 
  1. At first you are add statically translations for language A.
  2. Additionally you are defining a standard url loader.
  3. And finally you are setting A as preferred one.
2. You are switching the language B.
  1. The new translation will be loaded and everything is okay.
3. You are invoking a `refresh()`
  1. Until now: Only B will be refreshed because it is active. A will be untouched and still be available.
  2. With your change: Both A and B will be discarded. A will be fetched by the loader the *first time* on next demand.

Yeah, this change is intended, but the result could be a problem for anyone using the default static provisioned translations only for static defaults (in case of issues while determining the correct language). Perhaps an opt-in is better..  `refresh(true)`

**Comment by DWand** [comment] 2015-04-19 00:13
@knalli, but we do already have a parameter to specify a language to be updated.

Is the use case you've mentioned common? It looks more like workaround.

Consider the partial loader is used in the application. If we want to refresh translation tables as a result of structural changes in the loader the first scenario will cause real bugs, while the second one might add some uncomfortable delays. Also, this loader provides an ability to specify static parts - they'll be fetched without any xhr requests.

**Comment by knalli** [comment] 2015-04-19 16:27
I'm only saying this could cause trouble for some. I would highlight this at least in the release notes. IMHO the translations should be always available via a loader or never. The mixed mode is not really supported (well, it works using the method I've described).

**Comment by DWand** [comment] 2015-04-20 23:05
@knalli, such behavior is actually documented in our API docs :smile: So, yeah, this is definitely a bug.

**Comment by knalli** [comment] 2015-04-21 07:28
Huh? Where? Also in the code on api level?

**Comment by DWand** [comment] 2015-04-21 07:52
@knalli, it is mentioned here:

* links to the current master tree: https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/src/service/translate.js#L1590-L1592 and https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/src/service/translate.js#L1602

* links to the current canary tree: https://github.com/angular-translate/angular-translate/blob/3facb92487efab8f4a7ed6a2eac6c9812f1c01b9/src/service/translate.js#L1657-L1659 and https://github.com/angular-translate/angular-translate/blob/3facb92487efab8f4a7ed6a2eac6c9812f1c01b9/src/service/translate.js#L1669

That's why, I think, this issue can be considered as a bug - the current behavior differs from what is documented.

**Comment by knalli** [comment] 2015-04-21 08:05
Ok.

**Comment by DWand** [comment] 2015-04-24 18:28
@gsaini, some changes were merged to the `canary` branch. Can you check whether the issue is solved?

**Comment by gsaini** [comment] 2015-04-30 03:53
@knalli @DWand - I am getting the below issue after using the angular-translate.js (build of canary branch from dist folder).

TypeError: preferred.split is not a function
    at negotiateLocale (angular-translate.js?dc=1430365756901:183)
    at Function.$get.$translate.use (angular-translate.js?dc=1430365756901:1563)
    at Object.app.config.getTranslateKeys (states.js?dc=1430365756901:45)
    at Object.invoke (angular.js?dc=1430365756901:4169)
    at proceed (angular-ui-router.js?dc=1430365756901:411)
    at invoke (angular-ui-router.js?dc=1430365756901:407)
    at study (angular-ui-router.js?dc=1430365756901:386)
    at $Resolve.resolve (angular-ui-router.js?dc=1430365756901:490)
    at resolveState (angular-ui-router.js?dc=1430365756901:2889)
    at Object.transitionTo (angular-ui-router.js?dc=1430365756901:2601)

**Comment by knalli** [comment] 2015-04-30 07:12
@gsaini : Using http://plnkr.co/edit/S0rxYOJRReUDGeLwWXlr?p=info as boilerplate, you can please make a test case?

**Comment by knalli** [comment] 2015-05-02 20:00
Anyway. Fixed that possible npe 1aaab98, however, I'm quite not sure why `getLocale()` should return non string.

**Comment by knalli** [comment] 2015-05-02 20:00
And rest was done already. Closed.

**Closed by knalli** 2015-05-02 20:00 UTC
