### ISSUE TITLE
Switching language dynamically using $translate.use doesn't work

### ISSUE THREAD

**Issue by tilwinjoy** [angular-translate/angular-translate#1417] opened 2016-02-25 10:35 UTC
My default language is english, selected language is german.

When I try to switch back to english, the language doesn't switch due to below code:

    else if (langPromises[key]) {
          // we are already loading this asynchronously
          // resolve our new deferred when the old langPromise is resolved
          langPromises[key].then(function (translation) {
            if (!$uses) {   // <<------------------------ WHY THIS?
              useLanguage(translation.key);
            }
            deferred.resolve(translation.key);
            return translation;
          }, function (key) {
            // find first available fallback language if that request has failed
            if (!$uses && $fallbackLanguage && $fallbackLanguage.length > 0) {
              return $translate.use($fallbackLanguage[0]).then(deferred.resolve, deferred.reject);
            } else {
              return deferred.reject(key);
            }
          });
        }`

`langPromises[key] exists`, which is a promise for english language data.
We attach a handler to it via `then()` which gets resolved immediately since it's an already resolved promise. Now, value of `$uses`  is the language key for german. So below code in that success callback prevents me from switching to  english:

      if (!$uses) { 
              useLanguage(translation.key);
      }

Can someone explain why this code is in place..? If I'm using a language (`$uses` has some value) I can't switch to an already loaded language..?

###  environment
angular-translate angular-translate and it's plugins - v2.9.2 - 2016-02-21
angular 1.3.5 
angular-cookies v1.3.5

### Expected behaviour
Language should switch to english when I invoke `$translate.use('en')` regardless of whether it was already loaded or I'm using a different language.

### Actual behaviour
Language doesn't switch.

**Comment by tspaeth** [comment] 2016-02-25 10:41
Can you setup a short plnkr, so we have a valid testcase showing all configuration you have? thanks.

**Comment by tspaeth** [comment] 2016-02-25 16:09
Ok. Got it. 

Yes, the line you marked looks incorrect also to me. @knalli any reason for pushing in that if-section lately?

**Comment by tspaeth** [comment] 2016-02-25 16:14
Duplicate of #1415 - closing in favor of this

**Closed by tspaeth** 2016-02-25 16:14 UTC
Labels: duplicate
