### ISSUE TITLE
When using partial translations and multiple translate.refresh() are called not all translations are loaded

### ISSUE THREAD

**Issue by cleavera** [angular-translate/angular-translate#1326] opened 2015-12-09 15:39 UTC
When I call $translatePartialLoader.addPart('...') and translate.refresh() in a short space of time the full list of translations is not always loaded in, this leads to the end user being shown missing translations.

The issue seems to happen when you add a part then refresh translations then add another part and refresh it before the previous refresh has completed. If the second refresh is completed then the first is completed then the results of the second refresh are ignored as the first one (with less data) overwrites the data from the second (which has the extra data).

Hopefully this example makes it clearer.
http://codepen.io/antisback/pen/xZGKQK?editors=101
You can toggle the translation working by commenting out the timeout near the end to simulate the first refresh resolving after the second.

**Comment by tspaeth** [comment] 2015-12-09 21:56
Is it a duplicate of https://github.com/angular-translate/angular-translate/issues/1307 ?

**Comment by cleavera** [comment] 2015-12-10 10:24
No this is more about when the requests are returned out of order and some translations are lost.

eg. P = Promise, T=Partial translation
Request: P1(T1), P2(T1, T2), P3(T1, T2, T3)
Response: P1(T1), P3(T1, T2, T3), P2(T1, T2)
Available translations: T1, T2
Then if you manually then perform another translation refresh:
Available translations: T1, T2, T3

**Comment by knalli** [comment] 2015-12-27 16:53
@cleavera Just picked your PR. Thank you !

**Closed by knalli** 2015-12-27 16:53 UTC

**Comment by cspeer** [comment] 2016-02-14 13:38
Hi there,

is there a release date for 2.9.2? I would really like to see this fix released soon :+1: 

Thanks,
Chris

**Comment by knalli** [comment] 2016-02-14 13:40
Uhm.. (confused) this is part of 2.9.0 already?

**Comment by cspeer** [comment] 2016-02-14 13:47
Well,... never mind. I don't know why I thought this would be added in 2.9.*2*

Thanks!

**Comment by amit1911** [comment] 2017-07-26 01:04
hi, is this issue fixed? I am still facing this issue in 2.15. I am on angular 1.26 btw but using v2.15 for angular-translate. Should i be using a different version of angular translate for angular v 1.26?

**Comment by knalli** [comment] 2017-07-26 05:58
Looks so. Please file a new issue if the bug is still unresolved. And attach an appropriate demo, thanks.
