### ISSUE TITLE
Missing interpolation of default translations

### ISSUE THREAD

**Issue by armyofda12mnkeys** [angular-translate/angular-translate#1602] opened 2016-09-30 17:44 UTC
### Subject of the issue

In my database I store translations for angular to be pulled dynamically (on the 1st page of our Single Page App), and then just use angular-translate either in our templates or sometimes in our JS code (via $translate.instant() method to pull the translation gotton via the 'resolve' of the 1st controller).
My question is about the JS code.

My code below works if there is no translation in the database since the string will manually be  'otherwise will close in {{dialog_countdown_timer}} seconds'.
But if there is a translation, then $translate.instant runs and instantly tries to translate the {{dialog_countdown_timer}} variable, but that is a scope variable i want to 'stay' and allow the angular $scope to update it 

```
var glossary_after_close_button = $translate.instant('glossary.popup.after.close.button')=='glossary.popup.after.close.button' ? 'otherwise will close in {{dialog_countdown_timer}} seconds' : $translate.instant( 'glossary.popup.after.close.button');
...
//popup html created through directive
popup_html += '<div id="glossary-popup-timer">'+ glossary_after_close_button +'</div>';

 var mobile_dialog = ngDialog.open({
          template: popup_html,
          plain: true,
          scope: $scope
        });

var everySecond = $interval(function(){
          console.log('updates the popup string with counttdown variable');
          $scope.dialog_countdown_timer = $scope.dialog_countdown_timer - 1;
....
});
```
### Your environment
- angular v1.4.9
- angular-translate v2.12.1
- chrome (version: 53.0.2785.116 m) [shouldnt matter]
### Steps to reproduce

Here is a basic example: https://plnkr.co/edit/FpxCrnczg1yL4DROPhiD?p=preview
### Expected behaviour

It would be cool for a way to ask for an instant translation but not interpolate the {{scope}} variables. Is there a way to do this?
### Actual behaviour

$translate.instant() removes the variable instantly in my directive's code, so the glossary popup I have only shows 'otherwise will close in  seconds'. Makes sense since its called instant :) , but hoping there's a way to get passed this.

**Comment by knalli** [comment] 2016-10-01 18:20
We do interpolation and and the api does not allow disabling this as its part of the core features.

If I get this right, you are actually providing default values. Perhaps you should read in our docs/guide about providing default or fallback translations?

**Comment by armyofda12mnkeys** [comment] 2016-10-02 20:38
Let me try using an actual template with the variable in it vs manual html to pass the ngDialog. That might solve my issue. Will let you know Monday if it works.

**Comment by armyofda12mnkeys** [comment] 2016-10-05 18:35
so now I use templates (vs the translate.instant code i had above) completely, but still doesn't work: 
`<div class="center-block mobile-def-countdown-timer" translate="glossary.popup.after.close.button" translate-default="otherwise will close in {{dialog_countdown_timer}} seconds"></div>`

When there is no translation, it works. it pulls the scope variable into the translate-default attribute's translation and I see a countdown of the $scope.dialog_countdown_timer variable 10..9..8....1 seconds. 
But when there is a translation in my database, it still does immediate resolution of the variable the 1st time translations are loaded in the app via the $translateProvider.useLoader('translationLoader'); code (which gets the translations from a Web Service which gets from our database).


In Chrome debugger, i can see the key below has the {{dialog_countdown_timer}} literally when passed to the deferred.resolve(translations); line:
glossary.popup.after.close.button : "sonst wird geschlossen in {{dialog_countdown_timer}} Sekunden"

```
$translateProvider.useLoader('translationLoader'); 
...
angular.module('questionniareApp').factory('translationLoader', function ($q, $rootScope) {

  return function (options) {
    var deferred = $q.defer(),
        translations; //loop over translations returned by web service (passed into options) and assign to object-key lookup table.

    translations = $rootScope.webserviceObject.translationMap;

    deferred.resolve(translations);
    return deferred.promise;
  };

});

```

I may have to go back to not using templates (and have "sonst wird geschlossen in ### Sekunden") in the database which then i'd use translate.instant('glossary.popup.after.close.button').replace('###','{{dialog_countdown_timer}}') ). and go back to hardcoding the html string to pass to ngDialog vs a template with translate attributes.

**Comment by tspaeth** [comment] 2016-10-06 19:54
Hm. I'm a little bit irritated about the whole  blocks in the first and last comment here. The webserviceObject is expected to be async, huh? So the loader might catch... nothing? And how does it catch multiple languages here? 

And in general I'm wondering what the special corner case is here?
You're fetching some async translations containing variables that need to be interpolated with content coming from your application or elsewhere, right? Something special added?

**Comment by armyofda12mnkeys** [comment] 2016-10-07 23:00
@tspaeth 

> The webserviceObject is expected to be async, huh? So the loader might catch... nothing? And how does it catch multiple languages here?

hmmm well it seems to work every single time (loading the translations at least be4 my app gets viewed). 
The web service resolves an object before the view is served that holds the translationMap (and locale).
if  $translateProvider.useLoader() is async, not sure how it works 100% of the time I've tested it... Here is the app's simplified structure:
Maybe optimally I'd set the translations inside the resolve since it will have webserviceObject.translationMap available.
Sorry for the bunch of code, I tried to cut as much of it down as possible to make it barebones.

>You're fetching some async translations containing variables that need to be interpolated with content coming from your application or elsewhere, right? 

The webserviceObject brings back what was in the DB so pretend the 'translations = $rootScope.webserviceObject.translationMap;' line really gets this object back: 
`{'button.back-text' : 'ZURÜCK', 'button.next-text' : 'WEITER', 'glossary.popup.after.close.button': 'Schließt in Sonst {{dialog_countdown_timer}} Sekunden'}
`
Then I just use 'glossary.popup.after.close.button' in my template and it doesn't show the dialog_countdown_timer $scope variable.

app.js:
```
angular.module('screenerApp', [
  ...
  'ngRoute',
  'ui.router',
  'pascalprecht.translate',
])
.config( function ($urlRouterProvider, $stateProvider , $translateProvider) {

  $translateProvider.useLoader('translationLoader');//before the /questionnaire/question-1 is served... this seems to be done? if asynchronous, maybe its just so quick that it will usually load be4 /questionnnaire/question-1 is returned (since the url has to start off /welcome/screenerId=101 before it gets redirected to that '/questionnnaire/question-1' state/view )
  //maybe I should synchronously be setting the translation array in the resolve below where I get the web service object
  //still dont get how it knows to run after the getFirstQuestionController is done setting the $rootScope.webserviceObject

//when does this get run? it seems to always run when rootScope
angular.module('screenerApp').factory('translationLoader', function ($q, $rootScope) {
  return function (options) {  
    var deferred = $q.defer(), 
    translations; //loop over translations returned by web service (passed into options) and assign to object-key lookup table.

    if ( !($rootScope && $rootScope.webserviceObject) ) {//set in the getFirstQuestionController, NOTE: will change to a service soon so doesn't store in the $rootScope! since that seems like bad practice
      translations = {};
    } else {
      translations = $rootScope.webserviceObject.translationMap;
    }

    deferred.resolve(translations);
    return deferred.promise;
  };

});

  
  $stateProvider
  .state('welcome', {
        url: '/welcome', 
        ...
        controller: 'getFirstQuestionController'
        resolve: { //resolve the json obj from the Web Service be4 going the controller/view
         'firstQuestion':  function($q, webService) {
            var deferred = $q.defer();
            var url = window.location.href;
            var query_string =  url.substring( url.indexOf('?') );
            var param_map = URI.parseQuery(query_string);          
            
            webService.sendData( param_map.screenerId ).then(function(successResponse) {
              deferred.resolve(successResponse.data); //gets the 1st question for questionnaire, but also returns other things like the translations in the JSON webserviceObject.translationMap
            });
            return deferred.promise;
          }
        }
  }
  .state('questionnaire', {//for urls like /questionnaire/question-101
        url: '/questionnaire/{id}',
        views: {
          'main': {
            templateUrl: 'views/main.html',
            controller: 'getQuestionController'
          }
        }
  }

};
```

getFirstQuestionController.js:
```
'use strict';
angular.module('questionniareApp')
.controller('getFirstQuestionController', function($translate, firstQuestion, cacheService) {
  //some setup for variables for the view
  $rootScope.webserviceObject = firstQuestion;  
  cacheService.startNewQuestionnaireCache(); //clear out clientside localstorage cache of the questionnaire since they starting a new questoinnaire
  ...
  
  //Note!!!: this probably isn't needed since the translationLoader just loads strings for the language dynamically returned by the web service 
  //  (translationLoader doesn't seem to need to be offered an JSON object like {'en-US': {...key/value translations for englishUS}, 'es-CA': {...key/value translations for spanishMexico},...etc}) but just takes {...key/value translations for the current language} so hence why below probably not needed
  $translate.use(firstQuestion.locale); //setup the default language for the questionnaire which is returned via the web service (our webservice object send back will know whether screener '101' is a fr-CA study for example and return that locale object)
  
  $state.go('questionnaire', { goes immediately to /questionnaire/$id questionnaire/question1 in the url so user doesn't see /welcome/?screenerId=101 in the url but the actual 1st question
      qid: ('question-'+ firstQuestion.question_id) //will have question info in nextQuestion
  });
  
}
```


getQuestionController.js 
```
//every question gets this controller as the getFirstQuestionController is only for setting things up.

'use strict';
angular
.module('questionniareApp')
.controller('getQuestionController', ['$scope', '$state', '$stateParams', 'cacheService', '$rootScope']) {

  var url_id =  $stateParams.id; 	
	var real_question_id = url_id.slice(url_id.indexOf('-')); //try to get question-id from question-1 (should return 1 for example in that case)
	
  if(!cacheService.inCache(real_question_id)) {
    $scope.currentquestion = cacheService.getFromCache(real_question_id); //pull from localStorage
  } else {
    $scope.currentquestion = $rootScope.webserviceObject;
    cacheService.addQuestionToCache(real_question_id, questioninfo); //key val to send to cache so if user hits the back button in the SPA will get the question from the localstorage cache (vs re-getting it from the Web Service to save time)
  }

}
```

**Comment by knalli** [comment] 2016-10-08 17:25
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment] 2016-10-09 16:49
Sorry, you have had already provided a demo. I was flashed with the code above. Sorry about this.

I think I got it: The problem is default texts are not interpolated with the interpolation params. At the moment, they are treated as static default texts.

I can see the benefit of interpolate defaults also. We are welcome a contribution. :)

**Comment by armyofda12mnkeys** [comment] 2016-10-10 04:57
>I think I got it: The problem is default texts are not interpolated with the interpolation params. At the moment, they are treated as static default texts.

Well in a separate but similar issue, templates didn't work for me for non-default (German) texts.
and $template.translate() in my original plunkr/1st post didn't work for non-default (German) texts.
so its actually when it **doesn't** use the default where there is an issue.

I think it auto-interpolates them at some point earlier than I'd want. 
For example generally what i want to do, is in this example I made http://plnkr.co/edit/OnR9oA?p=preview, under this area (the only difference being I am pre-loading all my translations at beginning of the app): 

> "Seconds: 3 seconds.
> Seconds: 3seconds.
> DEFAULT(used since translation not available): Seconds: 3 seconds."

So why does the above work; and whether I use $translate.translate() or templates, it doesn't work for me when it tries to display the same countdown text that was loaded earlier via useLoader...
My theory is the custom loader $translateProvider.useLoader('translationLoader'); auto-interpolates the variable at the beginning of the app and removes {{dialog_countdown_timer}} so I can't use that full translation later in my actual 'countdown-popup' template later in the app which is looking for the variable. Does that sound about right?
I can create an other plunkr that shows the issue pop up via a custom loader maybe as that is probably the real issue.

P.S. Im going to remove all that code I put a few posts back, as it gets super track.

**Comment by knalli** [comment] 2017-06-25 17:12
Putting together:

`<div translate="glossary.popup.after.close.button" translate-default="otherwise will close in {{dialog_countdown_timer}} seconds"></div>`

This will work because the text will be interpolated by AngularJS template system. Actually, this *is* static text for angular-translate.  And said this, it means we do not provide interpolated default texts at the moment. Maybe this is a contribution worth.

> My theory is the custom loader $translateProvider.useLoader('translationLoader'); auto-interpolates 

Nope, the loader does not even know something about interpolation. And he should not.

**Comment by knalli** [comment] 2017-06-25 17:15
> PS if a web service obj is returning an object (key, values of translations), is what Im doing correct loading them via $translateProvider.useLoader?

If your data contains a translation id like `id = 'userName'`, you can use it in three ways with angular-translate built-ins: 
1. Available in `scope.id`: `<span translate="{{id}}"</span>`
2. Available in `scope.id`: `{{id || filter}}`
3. `$translate(id)`, `$translate.instant(id)`

**Closed by knalli** 2017-06-25 17:15 UTC
Labels: Contribution Welcome, enhancement
