### ISSUE TITLE
Issue on filter translate. 

### ISSUE THREAD

**Issue by gladsonrobinson** [angular-translate/angular-translate#1257] opened 2015-10-13 07:24 UTC
Have used {{'CONTENT_ID_TO_TRANSLATE' | translate}}. My requirement is to select more than 1 languages.

I have used $translate.use('selected_language') inside my controller on selecting a new language. But its not working and have gone through some code like

$translate.instant('CONTENT_ID_TO_TRANSLATE'); 

But its not updating my template. And have log list of data to translate so I cant use $translate.instant for every content id.

**Comment by knalli** [comment] 2015-10-13 09:55
No, we have not such a feature right now. However, it will be part of v3. See any process of this at #995 (wip).

Closed because of duplicate of #500

**Closed by knalli** 2015-10-13 09:55 UTC
