### ISSUE TITLE
Partial Loader Not Interpolating Values On First Page Load

### ISSUE THREAD

**Issue by mej1d** [angular-translate/angular-translate#1645] opened 2016-11-11 00:43 UTC
### Subject of the issue
I'm making use of the translate directive, partial loader, loader cache, and the gulp-ng-lang2js tool. When I navigate to a page for the first time, the IDs are not interpolated. If leave the page and come back, they will be interpolated. Translation IDs will also be interpolated if I go directly to the page by URL.

This is what my configuration looks like: 

```
$translateProvider
        .useLoader('$translatePartialLoader', {
          urlTemplate: 'i18n/{part}/lang/{lang}.json'
        })
        .useSanitizeValueStrategy('sanitize')
        .fallbackLanguage('en')
        .preferredLanguage('en')
        .useLoaderCache('$translationCache')
        .forceAsyncReload(true);

angular.module("myApp")
  .run(["$rootScope", "$translate",
    function($rootScope, $translate) {
      $rootScope.$on('$translatePartialLoaderStructureChanged',
        function() {
          $translate.refresh();
        });
    }
  ]);
```

I have pulled $translationCache into my controller and found it does indeed contain the cached table on first load. I am calling `$translatePartialLoader.addPart()` in the controller. I watch the network tab in Chrome Devtools and verified that no call is made to the server to get the translation table.

Essentially what I am finding is that `$translatePartialLoader.addPart()` MUST be called before loading the controller and not within the controller, even though I have already cached the translation table.

What is going on?

### Your environment
* version of angular-translate ^2.12.1
* version of angular 1.5.8
* which browser and its version Chrome 54.0.2840.90

### Steps to reproduce
Working on a Plunker

### Expected behaviour
The ID's should be interpolated on first load.

### Actual behaviour
The IDs are not interpolated on first load, but are interpolated when returning to the page.

**Comment by Naimikan** [comment] 2016-12-12 10:47
+1!

**Comment by mehjid** [comment] 2016-12-12 15:32
Hey Naimikan, here's a workaround I found in another issues thread. It's a bit awkward but seems to be working. Basically we now rely on adding translation in the resolve config option of a [route declaration](https://docs.angularjs.org/api/ngRoute/provider/$routeProvider). Since $translate.refresh() returns a promise, we can delay loading a page until we confirm the translations have resolved.

It is also recommended that you create a helper service to reduce boilerplate:

```
(function() {
  "use strict";

  angular.module("app")
  .factory("translationResolver", ["$translatePartialLoader", "$translate",
      function($translatePartialLoader, $translate) {
        return function() {
          angular.forEach(arguments, function(translationKey) {
            $translatePartialLoader.addPart(translationKey);
          });
          return $translate.refresh();
        };
      }
  ]);
})();
```

Your route declaration will look like this:

```
  angular
    .module("app")
    .config(["$routeProvider", function($routeProvider) {
      $routeProvider.when("/app/my-page", {
        template: '<my-page></my-page,
        resolve: {
          translations: ["translationResolver",
              function(translationResolver) {
                return translationResolver('i18n/my-page');
              }]
        }
      });
```

**Comment by mtwar** [comment] 2017-01-07 01:36
The problem here is that the promise for the language is not reassigned during refresh, so $translate incorrectly reports that the translations are loaded for the table that the partial loader is updating. I have a fix and will post it as soon as I figure out why I don't have permission to push to the repository:

![image](https://cloud.githubusercontent.com/assets/22204584/21738208/90d0d486-d436-11e6-9c6e-b4d6202f6bd4.png)

**Comment by mtwar** [comment] 2017-01-24 08:18
The fix I made for this also causes a regression where the translate cloak directive will not decloak on the first load of a particular part. This is due to a problem in the way the promises from loadAsync are handled in refresh. The $q.all promise resolves after all of the handlers on the individual promise queues, which will always cause determineTranslation to have a cache miss on the first call to $translate after a part is added, this first call being the one from the translate-cloak directive. The fix is to just add the translations call (to update the global table) to each promise queue individually before the q.all promise is established. I'll include this as well with the other fix I mentioned previously. I think I now have two for translate-cloak, two for refresh, and one for the partial loader that together make them behave sanely together. I'll be sure to post them soon; bug me if I don't!

**Comment by mtwar** [comment] 2017-02-07 01:20
Fix here: https://github.com/angular-translate/angular-translate/pull/1688

**Closed** 2017-02-12 00:42 UTC
