### ISSUE TITLE
One-time binding and load static files do not translate

### ISSUE THREAD

**Issue by studentIvan** [angular-translate/angular-translate#1450] opened 2016-03-25 11:05 UTC
### Subject of the issue
One-time binding in filter and load static files do not translate before ui-router navigate somewhere

### Your environment
* angular-translate 2.10
* angular.js 1.5.0
* latest google chrome linux xubuntu

### Steps to reproduce
This plunkr reproduce main issue: https://plnkr.co/edit/SJtSpPSlQddpfd3plDlx?p=preview
Just see one-time binding and many times binding how they work.

### Expected behaviour
Translate should load static translation and apply it to even one-time bindings. Because one-time bindings it is an performance solution.

### Actual behaviour
However we see nothing translation for block {{:'hello'|translate}}
But only before ui-router navigate somewhere and back

**Comment by knalli** [comment] 2016-03-25 13:11
Your expectation is not right when using one-time binding.

If you want to use one-time-binding, the filter will be evaluated only one time (well, the filter's feature is naming it). Any later loadings cannot be resolved again.

That is why one-time-binding + asynchronous loading of translations cannot work by design. You cannot have both.

However, if you can ensure the filter will be called *after* the translations are already loaded, perhaps you will have a solution. But this requires a custom setup, perhaps with a combination of your router/resolving events.

**Closed by knalli** 2016-03-25 13:11 UTC

**Comment by studentIvan** [comment] 2016-08-03 17:42
Solution here https://atticuswhite.com/blog/angularjs-translate-once-angular-translate-one-time-binding/
